### PR TITLE
rename GVFS to RGFS, fix #7

### LINKED ISSUE #7: GVfs name is already taken guys
The GNOME Virtual File System (GVfs) is already a well established thing and is in Wikipedia https://en.wikipedia.org/wiki/GVfs. It would be polite to consider a different name for Microsoft GVFS.

### PR DESCRIPTION
**Pull request by illwieckz**
This is a renaming example based on suggestion found there:
https://github.com/Microsoft/GVFS/issues/7#issuecomment-345408487

Note that RGFS name is not my own idea but that name fits the need.
If you prefer another name, it wouldn't be hard to adapt the following renaming script and run it on the whole tree.

This was done doing:

```sh
git ls-files | xargs -n1 -P1 dirname | grep GVFS | sort -u | sed -e 's/GVFS/RGFS/g' | xargs -n1 -P1 mkdir -p
git ls-files | grep GVFS | sed -e 'p;s/GVFS/RGFS/g' | xargs -n2 -P1 git mv
git ls-files | grep Gvfs | sed -e 'p;s/Gvfs/Rgfs/g' | xargs -n2 -P1 git mv
git clean -df
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 sed -e 's/gvfs/rgfs/g;s/gvFS/rgFS/g;s/Gvfs/Rgfs/g;s/GVFS/RGFS/g' -i
git add .
```

You can check everything is renamed that way:

```sh
git ls-files | grep -i gvfs
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 grep -Hi gvfs
```

### CODE REVIEW

**Comment by illwieckz** [comment]
Note that I signed the Microsoft CLA but it's unneeded for that change: there is nothing that can be considered as original since there is only one way to do it.

**Comment by sanoursa** [comment]
Thanks for the PR and for including your script, but we're not going to make a name change at this time.

**Comment by illwieckz** [comment]
I just pushed two commits to also rename `GVFlt` to `RGFlt` and `GvLib` to `RgLib` to be consistent with the `GVFS` to `RGFS` renaming.

This way the day you want to make a name change you just have to merge this PR or run the scripts. :wink:

By the way I'm a bit surprised to discover there was no new commit in master since the day I proposed this PR so I wonder what's happening since it was said in #17 that people were fully invested in R&D efforts.

The `GvFlt` to `RgFlt` renaming was done doing:

```sh
git ls-files | xargs -n1 -P1 dirname | grep GVFlt | sort -u | sed -e 's/GVFlt/RGFlt/g' | xargs -n1 -P1 mkdir -p
git ls-files | xargs -n1 -P1 dirname | grep GvFlt | sort -u | sed -e 's/GvFlt/RgFlt/g' | xargs -n1 -P1 mkdir -p
git ls-files | grep GVFlt | sed -e 'p;s/GVFlt/RGFlt/g' | xargs -n2 -P1 git mv
git ls-files | grep GvFlt | sed -e 'p;s/GvFlt/RgFlt/g' | xargs -n2 -P1 git mv
git ls-files | grep gvflt | sed -e 'p;s/gvflt/rgflt/g' | xargs -n2 -P1 git mv
git clean -df
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 sed -e 's/gvflt/rgflt/g;s/Gvflt/Rgflt/g;s/GvFlt/RgFlt/g;s/GVFlt/RGFlt/g;s/GVFLT/RGFLT/g' -i
```

You can check everything is renamed that way:

```sh
git ls-files | grep -i gvflt
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 grep -Hi gvflt
```

The `GvLib` to `RgLib` renaming was done doing:

```sh
git ls-files | grep GvLib | sed -e 'p;s/GvLib/RgLib/g' | xargs -n2 -P1 git mv
git ls-files | grep gvlib | sed -e 'p;s/gvlib/rglib/g' | xargs -n2 -P1 git mv
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 sed -e 's/gvlib/rglib/g;s/GvLib/RgLib/g;s/GVLIB/RGLIB/g' -i
```

You can check everything is renamed that way:

```sh
git ls-files | grep -i gvlib
git ls-files | xargs -n1 -P1 file | grep ':.*text' | cut -f1 -d: | xargs -n1 -P1 grep -Hi gvlib
```

Note that there is two remaining files containing some `GVFS`/`GvFlt` strings:

```
RGFS/RGFS.FunctionalTests/TestData/BackgroundGitUpdates/PersistentDictionary.edb
RGFS/RGFS.FunctionalTests/TestData/BackgroundGitUpdates/epc.log
```

These two files are not plain-text files and I don't know if they have some kind checksum mechanism in them or not. If not the strings can be substituted in them too since the new strings have the same length than the older ones.

**Comment by sam0x17** [comment]
@sanoursa this might as well be closed-source with this kind of attitude. At least give your reasoning for why Microsoft is so insistent on sticking with this name despite the overwhelming negative reception doing so has had. Something like "Microsoft has already put a ton of marketing $$$ into the name" would be a totally acceptable and understandable answer, but simply stating "we are not going to do this" with no explanation is frankly a dick move and going to deter people from wanting to contribute to or use this otherwise useful software. On that note, why not just admit that you didn't research this enough in the first place and accidentally used something that was taken?

**Comment by bet0x** [comment]
Well, if they can use names that OPEN SOURCE USES, We can use any copyright name from Microsoft right?

**Comment by illwieckz** [comment]
Well, there is law about names and trademarks are another topic than authorship (open source is a matter of the later) but laws are made for when kindness isn't enough and coercion is required. Is that a message from Microsoft telling coercion only matters?

**Pull request closed without merging**
